name: verify

permissions:
  contents: write
  pull-requests: write

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
    
    - name: Install Dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        cp ./.verify-helper/config_nodebug.toml ./.verify-helper/config.toml
        if ! oj-verify all; then
          cp ./.verify-helper/config_debug.toml ./.verify-helper/config.toml
          oj-verify all
          exit 1
        fi
